# Generated by Django 5.1.2 on 2025-03-11 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='response',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='address',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='city',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='country',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='Default', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(default='Default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='pin_code',
            field=models.CharField(default='Default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='state',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
